name: Build and test Angular web-application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.16.*
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.*
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build -- --prod
    - name: E2E
      run: npm run e2e -- --configuration=ci